"""create invoice template tables

Revision ID: 3e6260b79a4e
Revises: e87decba2cb6
Create Date: 2026-07-31 09:51:30.820019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3e6260b79a4e'
down_revision: Union[str, None] = 'e87decba2cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_system_template', sa.Boolean(), nullable=False),
    sa.Column('page_size', sa.Enum('A4', name='page_size'), nullable=False),
    sa.Column('layout_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_templates_user_id'), 'invoice_templates', ['user_id'], unique=False)
    op.create_table('invoice_template_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('field_type', sa.Enum('TEXT', 'NUMBER', 'DATE', 'CURRENCY', 'CUSTOM', name='field_type'), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('default_value', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['invoice_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'field_key', name='uq_template_field_key')
    )
    op.create_index(op.f('ix_invoice_template_fields_template_id'), 'invoice_template_fields', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_template_fields_template_id'), table_name='invoice_template_fields')
    op.drop_table('invoice_template_fields')
    op.drop_index(op.f('ix_invoice_templates_user_id'), table_name='invoice_templates')
    op.drop_table('invoice_templates')
    # ### end Alembic commands ###
