"""create_invoice_due_reminders_table

Revision ID: 5649ad6ab27c
Revises: f3g4h5i6j7k8
Create Date: 2026-08-27 11:38:56.754429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5649ad6ab27c'
down_revision: Union[str, None] = 'f3g4h5i6j7k8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_due_reminders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('reminder_date', sa.Date(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_to', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id', 'reminder_date', name='uq_invoice_due_reminder_date')
    )
    op.create_index(op.f('ix_invoice_due_reminders_invoice_id'), 'invoice_due_reminders', ['invoice_id'], unique=False)
    op.drop_index(op.f('ix_customer_contacts_customer_id'), table_name='customer_contacts')
    op.drop_constraint(op.f('uq_definition_categories_user_name'), 'definition_categories', type_='unique')
    op.drop_constraint(op.f('uq_definition_tax_rates_user_rate'), 'definition_tax_rates', type_='unique')
    op.drop_constraint(op.f('uq_definition_units_user_name'), 'definition_units', type_='unique')
    op.alter_column('invoice_customers', 'address',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('invoices', 'recipient_contact_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.drop_constraint(op.f('subscriptions_user_id_key'), 'subscriptions', type_='unique')
    op.drop_index(op.f('ix_user_sessions_jti'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_user_id_revoked'), table_name='user_sessions')
    op.drop_constraint(op.f('uq_user_sessions_jti'), 'user_sessions', type_='unique')
    op.create_index(op.f('ix_user_sessions_refresh_token_jti'), 'user_sessions', ['refresh_token_jti'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_refresh_token_jti'), table_name='user_sessions')
    op.create_unique_constraint(op.f('uq_user_sessions_jti'), 'user_sessions', ['refresh_token_jti'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_user_sessions_user_id_revoked'), 'user_sessions', ['user_id', 'revoked_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_jti'), 'user_sessions', ['refresh_token_jti'], unique=False)
    op.create_unique_constraint(op.f('subscriptions_user_id_key'), 'subscriptions', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('invoices', 'recipient_contact_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('invoice_customers', 'address',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.create_unique_constraint(op.f('uq_definition_units_user_name'), 'definition_units', ['user_id', 'name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_definition_tax_rates_user_rate'), 'definition_tax_rates', ['user_id', 'rate'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_definition_categories_user_name'), 'definition_categories', ['user_id', 'name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_customer_contacts_customer_id'), 'customer_contacts', ['customer_id'], unique=False)
    op.drop_index(op.f('ix_invoice_due_reminders_invoice_id'), table_name='invoice_due_reminders')
    op.drop_table('invoice_due_reminders')
    # ### end Alembic commands ###
